# Generated by Django 4.0.3 on 2022-03-20 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_time', to='base.time'),
        ),
    ]
